version: '3'
# "Composefile"のバージョン
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql_d:/var/lib/mysql
    container_name: golang_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      ##<GRANT USERとかやらなきゃダメかも？docker-compose時に最初からこれでいいのかはわからんから試す価値あり>
      #MYSQL_PASSWORD: xxxxx
      #MYSQL_USER: xxxxxx
      TZ: 'Asia/Tokyo'
  web:
    build: .
    container_name: golang_app
    volumes:
      - .:/go/src/myapp
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      BINDING: 0.0.0.0
    stdin_open: true
    tty: true

volumes:
  mysql_d: